name: Build and Push Docker Image

on:
  push:
    branches:
      - port

env:
  IMAGE_NAME: "wirewrex/test-image"
  IMAGE_TAG: "latest"
  DEPLOYED_CONTAINER_NAME: "deployed-container"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Deploy Docker container
      run: |
        docker run -d --name ${{ env.DEPLOYED_CONTAINER_NAME }} ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Commit new image from deployed container
      run: |
        docker commit ${{ env.DEPLOYED_CONTAINER_NAME }} ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Push new image to Docker Hub
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
